import {
    createDefaultModule, createDefaultSharedModule, DefaultSharedModuleContext, inject,
    LangiumServices, LangiumSharedServices, Module, PartialLangiumServices
} from 'langium';
import { ReqSpecGeneratedModule, ReqSpecGeneratedSharedModule } from './generated/module';
import { ReqSpecValidator, registerValidationChecks } from './req-spec-validator';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type ReqSpecAddedServices = {
    validation: {
        ReqSpecValidator: ReqSpecValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type ReqSpecServices = LangiumServices & ReqSpecAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const ReqSpecModule: Module<ReqSpecServices, PartialLangiumServices & ReqSpecAddedServices> = {
    validation: {
        ReqSpecValidator: () => new ReqSpecValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createReqSpecServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    ReqSpec: ReqSpecServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        ReqSpecGeneratedSharedModule
    );
    const ReqSpec = inject(
        createDefaultModule({ shared }),
        ReqSpecGeneratedModule,
        ReqSpecModule
    );
    shared.ServiceRegistry.register(ReqSpec);
    registerValidationChecks(ReqSpec);
    return { shared, ReqSpec };
}
